### ISSUE TITLE
Launch OLS with first test version of BDS ontology

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#23]
Dependent on alpha release of BDS ontology.
Ensure has Allen Institute branding on top.

See https://github.com/EBISPOT/ontotools-docker-config for config rqd for deployment

**Comment by dosumis** [comment]
* CL BDS_subset  [ Available soon - we're debugging release - will be available under http://purl.obolibrary.org/obo/cl/subsets/ ]
* NPO neurons  - @tgbugs Please provide a URL to resolve the OWL file.  Note - imports must be resolvable.
* PCL - https://data.bioontology.org/ontologies/PCL/submissions/9/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb (don't know if possible without apikey @BAevermann  is there a better URL to use?
* BDS ontology  - https://raw.githubusercontent.com/obophenotype/brain_data_standards_ontologies/master/bdscratch-full.owl
 
Let's not get hung up on the branding issue. Could take some time to sort out.  In the meantime I'm sure we could hash out some basic descriptive text to use.

**Comment by hrshdhgd** [comment]
These will be the additional information I'll need for each ontology to enter into the configuration file:

```
- id: 
    preferredPrefix: 
    title: 
    description: 
    uri: 
    base_uri:
      - 
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
```
Out of these, the `id`, `preferredPrefix`, `uri` and `base_uri` are straightforward (I think). I'll need preferred values for `title` and `description`. For starters I'll just have placeholders present which can be easily be changed in the future. I'm assuming the `synonym_property` and `definition_property` would be the same for all(?) Please correct me if I'm wrong with anything I've mentioned above.
