### ISSUE TITLE
Finalise spec for ROBOT template build configuration

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#33]
Aim: Spec a configuration for file that allows specification of all metadata required to build robot templates from a (transcriptomics drive) taxonomy

We currently have a simple table: [src/dendrograms/taxonomy_details.tsv](https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/dendrograms/taxonomy_details.tsv) with headers:

Taxonomy id | Description | Reference | DOI | Species | Brain_region
-- | -- | -- | -- | -- | --
CCN202002013 | Mouse MOp BICCN taxonomy using multiple RNA-Seq datasets | (Yao et al., 2020a) | doi:10.1101/2020.02.29.970558 | NCBITaxon:10090 | UBERON:0001384

This needs to be extended to include information that can be used to roll equivalent Class definitions with marker lists:   root nodes and corresponding gross classes from CL.

It may be better to use YAML for this config, rather than a table, with keys for the columns in the current config table + 

```yaml
root_nodes:
  - 
     node: CS202002013_123
     cell_type: CL:0011005
     location_relation: RO:0002100
  - 
    node: CS202002013_179
    cell_type: CL:0000679
    location_relation: RO:0002100
```

TODO: specify config as JSON_schema, allowing configs to be validated as well as providing a place for documentation.
