### ISSUE TITLE
Update spec for reification pattern branch

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#60]
STATUS: DRAFT
AIM: MVP

1. Make classes only for _descendants_ of root nodes that have a cell_set_preferred_alias. If a root node is also a leaf node, make class for this too.
2. Generation of these classes is driven by 3 robot templates and a DOSDP:
   (a) {taxonomy}_equivalent_reification.tsv - spec unchanged
   (b) A new ROBOT template: {taxonomy}_minimal_markers.tsv
   (c)  {taxonomy}_class.tsv # Same as denormalised_marker branch; but make sure only nodes with cell_set_preferred_alias.
   (c) A new DOSDP; brainCellRegionMinimalMarkers.yaml +tsv

**ROBOT template: {taxonomy}_minimal_markers.tsv**

ID |  Markers  | part_of | has_soma_location |
-- | --  | -- | --
ID | SC 'expresses' some % SPLIT=\| SC 'part of' some % | SC 'has soma location' some % |
http://www.semanticweb.org/brain_data_standards/AllenDendClass_CS202002013_124 |  {`\|` delimited minimal markers} | {brain_region} | {brain_region}

Where minimal markers come from: markers/{taxonomy}_markers.tsv
Location_relation is associated specified for all descendants of each  [root node in config table](https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/dendrograms/taxonomy_details.yaml#L11); and corresponds to a column header in this robot template.

DOSDP sketch:

```yaml

classes:
  "animal cell": "animal cell"
  "Vertebrata <vertebrates>": "NCBITaxon:7742"
  "regional part of brain": "UBERON:0002616"

relations:
  part_of: BFO:0000050
  in taxon: RO:0002162

vars:
  gross_cell_type: "'cell'"
  taxon: "'Vertebrata <vertebrates>'"
  brain_region: "'regional part of brain'"

data_vars: 
  - cell_set_preferred_alias: "xsd:string"
  - minimal_markers: "xsd:string" # A list of maker names delimited by ', '

label:
   text: "%s %s %s (%s)"
   vars:
      - cell_set_preferred_alias 
      - brain_region
      - gross_cell_type
      - species

comment: 
    text: "The minimal set of markers required to distinguish this cell type from other cell types in the %s is: %s."
    vars: 
      - brain_region
      - minimal_markers
  
logical_axioms:
   subClassOf: 
       - text: "%s"
          vars: 
              - gross_cell_type
        - text: "'in taxon' some %s"
           vars: 
              - species
```

Where gross_cell_type = `cell_type` associated with ancestor [root node in config table](https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/dendrograms/taxonomy_details.yaml#L11); brain_region and taxon are defined in the same config.
