### ISSUE TITLE
Config should specify location relation for each root term by referencing a ROBOT template header

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#63]
```yaml

   - Node: CS202002013_123
      Cell_type: CL:0011005
      Location_relation: has_soma_location

  - Node: CS202002013_112 
    Cell_type: CL:2000043
    Location_relation: part_of
```

Example implementation on equivalent_markers.tsv ROBOT template

ID | CLASS_TYPE | Evidence | Gross_cell_type | has_soma_location | part_of | ...
-- | -- | -- | -- | -- | -- | --
ID | CLASS_TYPE | AI RO:0002558 | C % | C 'has soma location' some % | C 'part of' some % ...
