### ISSUE TITLE
Define & implement MVP for definitions for workshop

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#98]
If the templating system is not in place in time, we will generate mock-ups for the workshop based on the specification here.

This spec assumes support for zero-many templating.

Here's is a pseudo-code example

```yaml

vars:
  - minimal_markers

internal_vars:
   - minimal_makers_cat: 
       function: cat
       delimiter: ', '
   - allen_makers_cat: 
       function: cat
       delimiter: ', '   

text: >
  A %s of the %s %s. These cells can be distinguished from other cells in the %s
  by their expression of: %s.  {These cells also express %s.} {These cells have projection type %s.}

vars:
  - gross_cell_type #Should be class level here
  - taxon
  - brain_region
  - brain_region
  - minimal_markers_cat
  - allen_makers_cat
  - projection_type

```
Where contents of {} are only filled if var is non-empty.

attempted moustache version
```yaml
text: >
  A %s of the %s %s. These cells can be distinguished from other cells in the %s
  by their expression of: %s.  {#minimal_markers These cells also express {minimal_markers}. /minimal_markers} ....
```
